lib/protectora_web/router.ex
defmodule ProtectoraWeb.Router do
  use ProtectoraWeb, :router
  use Plug.ErrorHandler

  import ProtectoraWeb.UserAuth

  require Logger

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {ProtectoraWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  pipeline :api do
    plug(:fetch_session)

    plug(:accepts, ["json"])
  end

  pipeline :auth do
    plug(:fetch_session)

    plug(ProtectoraWeb.Auth.Pipeline)
    plug(ProtectoraWeb.Auth.SetAccount)
  end

  # We put this pipe first to be redirected to this routes first. we can duplicate the scopes because this is lineal

  scope "/", ProtectoraWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/publicacion/new", PublicacionLive.Index, :new)
    live("/publicacion/:id/show/edit", PublicacionLive.Show, :edit)
    live("/animal/new", AnimalLive.Index, :new)
    live("/animal/:id/edit", AnimalLive.Index, :edit)

    live("/animal/:id/show/edit", AnimalLive.Show, :edit)
  end

  scope "/", ProtectoraWeb do
    pipe_through(:browser)

    live("/", IndexLive.Index, :index)
    live("/colaborar", IndexLive.Index, :new)

    live("/publicacion", PublicacionLive.Index, :index)
    live("/publicacion/:id", PublicacionLive.Show, :show)

    live("/animal", AnimalLive.Index, :index)
    live("/animal/:id", AnimalLive.Show, :show)

    live("/animal/:id/padrinamento/new", AnimalLive.Show, :new_padrinamento)
    live("/animal/:id/email", AnimalLive.Show, :email)

    live("/padrinamento/new", PadrinamentoLive.Index, :new)
  end

  defp handle_errors(conn, %{reason: %Phoenix.Router.NoRouteError{message: message}}) do
    conn |> json(%{errors: message}) |> halt()
  end

  defp handle_errors(conn, %{reason: %{message: message}}) do
    conn |> json(%{errors: message}) |> halt()
  end

  scope "/api", ProtectoraWeb do
    pipe_through(:api)

    # iniciar sesion
    post("/voluntario/sign_in", VoluntarioController, :sign_in)
    post("/voluntario", VoluntarioController, :create)

    get("/publicacion", PublicacionController, :index)
    get("/publicacion/:id", PublicacionController, :show)
    post("/colaborador", ColaboradorController, :create)
    post("/padrinamento", PadrinamentoController, :create)
    get("/animal", AnimalController, :index)
    get("/animal/:id", AnimalController, :show)

    # resources "/imaxe_pVoluntarioControllerublicacion", ImaxePublicacionController, except: [:new, :edit]
  end

  scope "/api", ProtectoraWeb do
    pipe_through([:api, :auth])

    get("/animal/:id/edit", AnimalController, :edit)
    put("/animal/:id", AnimalController, :update)
    patch("/animal/:id", AnimalController, :update)
    delete("/animal/:id", AnimalController, :delete)
    post("/animal", AnimalController, :create)

    get("/publicacion/:id/edit", PublicacionController, :edit)
    put("/publicacion/:id", PublicacionController, :update)
    patch("/publicacion/:id", PublicacionController, :update)
    delete("/publicacion/:id", PublicacionController, :delete)
    post("/publicacion", PublicacionController, :create)

    get("/voluntario", VoluntarioController, :index)
    get("/voluntario/:id", VoluntarioController, :show)
    get("/voluntario/:id/edit", VoluntarioController, :edit)
    put("/voluntario/:id", VoluntarioController, :update)
    patch("/voluntario/:id", VoluntarioController, :update)
    delete("/voluntario/:id", VoluntarioController, :delete)

    get("/voluntario/get/:id", VoluntarioController, :show)

    # Authorizated routes in HTTP
    get("/colaborador", ColaboradorController, :index)
    get("/colaborador/:id", ColaboradorController, :show)
    get("/colaborador/:id/edit", ColaboradorController, :edit)
    put("/colaborador/:id", ColaboradorController, :update)
    patch("/colaborador/:id", ColaboradorController, :update)
    delete("/colaborador/:id", ColaboradorController, :delete)

    get("/padrinamento", PadrinamentoController, :index)
    get("/padrinamento/:id", PadrinamentoController, :show)
    get("/padrinamento/:id/edit", PadrinamentoController, :edit)
    put("/padrinamento/:id", PadrinamentoController, :update)
    patch("/padrinamento/:id", PadrinamentoController, :update)
    delete("/padrinamento/:id", PadrinamentoController, :delete)

    resources("/rexistro", RexistroController, except: [:new, :edit])
    # resources("/padrinamento", PadrinamentoController, except: [:new, :edit])
    # resources("/colaborador", ColaboradorController, except: [:new, :edit])
  end

  # Other scopes may use custom stacks.
  # scope "/api", ProtectoraWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: ProtectoraWeb.Telemetry)
    end
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  ## Authentication routes

  scope "/", ProtectoraWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    # get("/users/reset_password/:token", UserResetPasswordController, :edit)
    # put("/users/reset_password/:token", UserResetPasswordController, :update)
  end

  scope "/", ProtectoraWeb do
    pipe_through([:browser, :require_authenticated_user])

    live("/publicacion/new", PublicacionLive.Index, :new)
    live("/publicacion/:id/edit", PublicacionLive.Index, :edit)

    live("/colaborador", ColaboradorLive.Index, :index)
    # live("/colaborador/new", ColaboradorLive.Index, :new)
    live("/colaborador/:id/edit", ColaboradorLive.Index, :edit)

    live("/colaborador/:id", ColaboradorLive.Show, :show)
    live("/colaborador/:id/show/edit", ColaboradorLive.Show, :edit)

    live("/voluntario", VoluntarioLive.Index, :index)
    live("/voluntario/new", VoluntarioLive.Index, :new)
    live("/voluntario/:id/edit", VoluntarioLive.Index, :edit)

    live("/voluntario/:id", VoluntarioLive.Show, :show)
    live("/voluntario/:id/show/edit", VoluntarioLive.Show, :edit)

    live("/padrinamento", PadrinamentoLive.Index, :index)
    live("/padrinamento/:id/edit", PadrinamentoLive.Index, :edit)

    live("/padrinamento/:id", PadrinamentoLive.Show, :show)
    live("/padrinamento/:id/show/edit", PadrinamentoLive.Show, :edit)
    live("/animal/:id/rexistro/new", AnimalLive.Show, :new_rexistro)
    live("/animal/:idrexistro/rexistro/edit", AnimalLive.Show, :edit_rexistro)

    live("/rexistro", RexistroLive.Index, :index)
    live("/rexistro/new", RexistroLive.Index, :new)
    live("/rexistro/:id/edit", RexistroLive.Index, :edit)
    live("/rexistro/:id", RexistroLive.Show, :show)
    live("/rexistro/:id/show/edit", RexistroLive.Show, :edit)
  end

  scope "/", ProtectoraWeb do
    pipe_through([:browser])

    delete("/users/log_out", UserSessionController, :delete)
  end
end

lib/protectora_web/live/animal_live/email.ex
defmodule ProtectoraWeb.AnimalLive.Email do
  use ProtectoraWeb, :live_component
  import Swoosh.Email
  alias Protectora.Animais.AdoptionEmail

  alias Protectora.Mailer
  require Logger

  @impl true
  def render(assigns) do
    ~H"""
    <div  class="w-full " >
    <h3 class="flex justify-center items-center  text-xl font-extrabold underline underline-offset-3 decoration-8 decoration-blue-400 ">Enviar petición de adopción</h3>

    <.form  class="flex flex-col mt-4 gap-4 max-w-5xl " let={f} for={@user} phx-target={@myself} phx-submit="send-email" id="email-form">

    <%= label f, :nome, "Indique o seu nome", class: "font-extrabold" %>
    <%= text_input f, :nome %>
    <%= error_tag f, :nome %>

    <%= label f, :telefono, "Indique o seu teléfono de contacto", class: "font-extrabold" %>
    <%= number_input f, :telefono, class: "font-extrabold"%>
    <%= error_tag f, :telefono %>

    <%= label f, :email, "Indique o seu email", class: "font-extrabold" %>
    <%= text_input f, :email %>
    <%= error_tag f, :email %>

    <%= label f, :nota, "Indique neste espazo a información a maiores ou os detalles que vexa precisos ó persoal da protectora", class: "font-extrabold" %>
    <%= textarea f, :nota, style: "height: 180px"  %>
    <%= error_tag f, :nota %>

    <div class="inline-flex text-white mb-4 bg-teal-500 border-0 py-2 px-6 focus:outline-none hover:bg-teal-600 rounded text-lg max-w-fit">
    <%= submit "Enviar petición" %>
    </div>
    </.form>
    </div>
    """
  end

  @impl true
  def update(assigns, socket) do
    {:ok,
     assign(socket,
       user: Protectora.Animais.AdoptionEmail.changeset(%AdoptionEmail{}),
       animal: assigns.animal,
       return_to: assigns.return_to
     )}
  end

  @impl true
  def handle_event("send-email", %{"adoption_email" => user}, socket) do
    case Protectora.Animais.AdoptionEmail.changeset(%AdoptionEmail{}, user) do
      %Ecto.Changeset{action: nil, changes: _, errors: [], data: _, valid?: true} ->
        deliver_adoption_request(user, socket.assigns.animal)

        {:noreply,
         socket
         |> put_flash(:info, "Petición de adopción enviada")
         |> push_redirect(to: socket.assigns.return_to)}

      changeset ->
        {:noreply, assign(socket, user: %{changeset | action: :insert})}
    end
  end

  defp deliver(recipient, subject, body) do
    email =
      new()
      |> to(recipient)
      |> from({"Protectora", "protectoratfg@gmail.com"})
      |> subject(subject)
      |> text_body(body)

    with {:ok, _metadata} <- Mailer.deliver(email) do
      {:ok, email}
    end
  end

  def deliver_adoption_request(
        %{
          "email" => email,
          "nome" => nome,
          "nota" => nota,
          "telefono" => telefono
        },
        animal
      ) do
    return =
      deliver("protectoratfg@gmail.com", "Ten unha nova adopción esperando", """

      ==============================

      Ten unha petición de adopción de:

      Nome: #{nome}
      Email de contacto: #{email}
      Teléfono: #{telefono}

      O nome do animal polo que se pregunta é:
      #{animal.nome}
      https://protectoratfg.gigalixirapp.com/animal/#{animal.id}


      O solicitante quere facer saber o seguinte: #{nota}

      ==============================

      Póñase en contacto con esta persoa cando poda ou comuníquese a outro voluntario.

      Por favor non responda a esta mensaxe, de precisar algunha axuda contacte coa organización.

      ==============================
      """)

    return
  end
end

lib/protectora_web/live/animal_live/form_component.ex
defmodule ProtectoraWeb.AnimalLive.FormComponent do
  use ProtectoraWeb, :live_component

  alias Protectora.Animais
  alias Protectora.Animais.{Animal, ImaxeAnimal}

  require Logger

  def upload_directory do
    Application.get_env(:protectora, :animais_directory)
  end

  def local_path(id, filename) do
    [upload_directory(), "#{id}-#{filename}"]
    |> Path.join()
  end

  @impl true
  def mount(socket) do
    {:ok,
     allow_upload(socket, :photo,
       accept: ~w(.png .jpeg .jpg),
       max_entries: 8,
       max_file_size: 2_000_000
     )}
  end

  @impl true
  def update(%{animal: animal} = assigns, socket) do
    changeset = Animais.change_animal(animal)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"animal" => animal_params}, socket) do
    changeset =
      socket.assigns.animal
      |> Animais.change_animal(animal_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"animal" => animal_params}, socket) do
    save_animal(socket, socket.assigns.action, animal_params)
  end

  def handle_event("cancel-entry", %{"ref" => ref}, socket) do
    {:noreply, cancel_upload(socket, :photo, ref)}
  end

  defp save_animal(socket, :edit, animal_params) do
    case Animais.update_animal(
           socket.assigns.animal,
           animal_params,
           &consume_upload_photos(socket, &1)
         ) do
      {:ok, {:ok, _animal}} ->
        {:noreply,
         socket
         |> put_flash(:info, "Animal actualizado correctamente")
         |> push_redirect(to: socket.assigns.return_to)}

      {:ok, {:error, %Ecto.Changeset{} = changeset}} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_animal(socket, :new, animal_params) do
    case Animais.create_animal(animal_params, &consume_photos(socket, &1)) do
      {:ok, {:ok, _animal}} ->
        {:noreply,
         socket
         |> put_flash(:info, "Animal creado correctamente")
         |> push_redirect(to: socket.assigns.return_to)}

      {:ok, {:error, %Ecto.Changeset{} = changeset}} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  defp ext(entry) do
    [ext | _] = MIME.extensions(entry.client_type)
    ext
  end

  defp put_photo_urls(socket, %Animal{} = animal) do
    {completed, []} = uploaded_entries(socket, :photo)

    urls =
      for entry <- completed do
        # IO.inspect entry
        Routes.static_path(socket, "/animais/#{entry.uuid}.#{ext(entry)}")
      end

    %Animal{animal | imaxe_animal: urls}
  end

  def consume_photos(socket, %Animal{} = animal) do
    consume_uploaded_entries(socket, :photo, fn meta, entry ->
      dest = local_path(entry.uuid, entry.client_name)
      File.cp!(meta.path, dest)

      path_name = String.replace(dest, "priv/static", "")
      {:ok, path_name}
    end)
  end

  def consume_upload_photos(socket, %Animal{} = animal) do
    {completed, []} = uploaded_entries(socket, :photo)

    case completed do
      [h | _] ->
        Enum.each(animal.imaxe_animal, fn el ->
          File.rm(Path.join(["priv/static", el.path_imaxe]))
        end)

      [] ->
        {:ok, []}
    end

    consume_uploaded_entries(socket, :photo, fn meta, entry ->
      dest = local_path(entry.uuid, entry.client_name)
      File.cp!(meta.path, dest)

      path_name = String.replace(dest, "priv/static", "")
      {:ok, path_name}
    end)
  end
end

lib/protectora_web/live/colaborador_live/form_component.ex
defmodule ProtectoraWeb.ColaboradorLive.FormComponent do
  use ProtectoraWeb, :live_component

  alias Protectora.Colaboradores
  @impl true
  def update(%{colaborador: colaborador} = assigns, socket) do
    changeset = Colaboradores.change_colaborador(colaborador)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"colaborador" => colaborador_params}, socket) do
    changeset =
      socket.assigns.colaborador
      |> Colaboradores.change_colaborador(colaborador_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"colaborador" => colaborador_params}, socket) do
    save_colaborador(socket, socket.assigns.action, colaborador_params)
  end

  defp save_colaborador(socket, :edit, colaborador_params) do
    case Colaboradores.update_colaborador(
           socket.assigns.colaborador,
           colaborador_params,
           :full_check
         ) do
      {:ok, _colaborador} ->
        {:noreply,
         socket
         |> put_flash(:info, "Colaborador actualizado correctamente")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_colaborador(socket, :new, colaborador_params) do
    case Colaboradores.create_colaborador(colaborador_params, :full_check) do
      {:ok, _colaborador} ->
        {:noreply,
         socket
         |> put_flash(:info, "Colaborador creado correctamente")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/protectora_web/live/colaborador_live/show.ex
defmodule ProtectoraWeb.ColaboradorLive.Show do
  use ProtectoraWeb, :live_view

  alias Protectora.Colaboradores

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:colaborador, Colaboradores.get_colaborador!(id))}
  end

  defp page_title(:show), do: "Detalles colaborador"
  defp page_title(:edit), do: "Editar colaborador"
end

lib/protectora_web/live/padrinamento_live/show.ex
defmodule ProtectoraWeb.PadrinamentoLive.Show do
  use ProtectoraWeb, :live_view

  alias Protectora.Padrinamentos

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:padrinamento, Padrinamentos.get_padrinamento!(id))}
  end

  defp page_title(:show), do: "Show Padrinamento"
  defp page_title(:edit), do: "Edit Padrinamento"
end

lib/protectora_web/live/padrinamento_live/index.html.heex
<div class=" flex flex-col justify-center mt-6">
<div class="flex justify-center items-center">
<h1 class="  mt-6 underline underline-offset-3 decoration-8 decoration-blue-400 dark:decoration-blue-600 text-2xl sm:text-4xl font-extrabold leading-none tracking-tight text-gray-900  dark:text-white">Lista de padriños</h1>
</div>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={"/padrinamento?padrinamentos=" <> to_string(@page_number)}>
    <.live_component
      module={ProtectoraWeb.PadrinamentoLive.FormComponent}
      id={@padrinamento.id || :new}
      title={@page_title}
      action={@live_action}
      padrinamento={@padrinamento}
      return_to={"/padrinamento?padrinamentos=" <> to_string(@page_number)}
    />
  </.modal>
<% end %>

<table  class="m-12 gap-2 border-spacing-2">
  <thead class="text-white">
    <tr class="bg-teal-400  table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0" style="height: 50px;">
      <th class="text-center mx-8 md:text-xl">Email</th>
      <th class="text-center mx-8 md:text-xl">Perioricidade </th>
      <th class="hidden md:table-cell text-center mx-8 md:text-xl">Perfil de colaborador</th>
      <th class=" hidden md:table-cell text-center mx-8 md:text-xl">Perfil do animal</th>


      <th></th>
    </tr>
  </thead>
  <tbody id="padrinamento">
    <%= for padrinamento <- @padrinamento_collection do %>
      <tr class='hover:bg-gray-100 table-row' id={"padrinamento-#{padrinamento.id}"}>
        <td class="text-center table-cell font-extrabold mx-6"><%= padrinamento.colaborador.email %></td>
        <td class="table-cell items-center justify-center text-center mx-6"><%= padrinamento.perioricidade %></td>
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
        <td class="hidden md:table-cell items-center justify-center text-center "><span  class="inline-flex items-center font-medium text-blue-500 dark:text-blue-400 hover:underline"><%= live_patch padrinamento.colaborador.nome, to: "/colaborador/" <> padrinamento.colaborador.id %><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mx-3">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
        </svg>
        </span></td>
        <td class="hidden md:table-cell items-center justify-center text-center  "><span  class="inline-flex items-center font-medium text-blue-500 dark:text-blue-400 hover:underline"><%= live_patch padrinamento.animal.nome, to: "/animal/" <> padrinamento.animal.id %><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 mx-3">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" />
        </svg>
        </span></td>

        <td class="flex flex-col justify-center items-center m-2 ">
          <span class="inline-flex items-center font-medium text-blue-600 dark:text-blue-500 hover:underline"><%= live_redirect "Detalles", to: Routes.padrinamento_show_path(@socket, :show, padrinamento) %></span>
          <span class="inline-flex items-center font-medium text-green-600 dark:text-green-500 hover:underline"><%= live_patch "Editar", to: Routes.padrinamento_index_path(@socket, :edit, padrinamento) %></span>
          <span class="inline-flex items-center font-medium text-red-600 dark:text-red-600 hover:underline"><%= link "Borrar", to: "#", phx_click: "delete", phx_value_id: padrinamento.id, data: [confirm: "Está seguro de querer eliminar a este padriñamento do sistema?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<nav class="border-t border-gray-200 mb-16  mx-12 ">
      <ul class="flex my-2 items-center justify-center">
        <li class="">
        <%= if  @page_number <= 1 do %>
          <a class="px-2 py-2 pointer-events-none text-gray-600" href="#" phx-click="nav" phx-value-page={@page_number - 1}>Ant</a>
        <% else %>
          <a class="px-2 py-2" href="#" phx-click="nav" phx-value-page={@page_number - 1}>Ant</a>
        <% end %>

        </li>
         <div class="w-44 md:w-[400px] flex flex-row overflow-hidden " style="width: fit-content;">
    <%= for idx <-  Enum.to_list(1..@total_pages) do %>
        <li class="">

        <%= if @page_number == idx do %>
          <a class="px-2 py-2 pointer-events-none text-gray-600" href="#" phx-click="nav" phx-value-page={idx}><%= idx %></a>
        <% else %>
          <a class="px-2 py-2" href="#" phx-click="nav" phx-value-page={idx}><%= idx %></a>
        <% end %>

        </li>
     <% end %>
     </div>
        <li class="">

        <%= if @page_number >= @total_pages do %>
          <a class="px-2 py-2 pointer-events-none text-gray-600" href="#" phx-click="nav" phx-value-page={@page_number + 1}>Seg</a>
        <% else %>
          <a class="px-2 py-2" href="#" phx-click="nav" phx-value-page={@page_number + 1}>Seg</a>
        <% end %>
        </li>
      </ul>
    </nav>

</div>